spring.application.name=foodweb_be

spring.datasource.url=${env.MYSQL_URL}
spring.datasource.username=${env.MYSQL_USER}
spring.datasource.password=${env.MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret = ${env.SECRET_KEY}